### ISSUE TITLE
Resolution in Animate_X_infer.yaml

### ISSUE THREAD

**Issue by jiaqiAA** [antgroup/animate-x#6]
Hi, thanks for your great work!
I found that the default resolution `[768, 480]` is portrait screen, how should I set the horizontal screen resolution? What principles should be followed when changing the resolution?

**Comment by luoxyhappy** [comment]
Same problem, have you solved it?

**Comment by jiaqiAA** [comment]
Add `resolution = [xx, xx]  self.resolution = resolution`, in `class UNetSD_Animate_X`

**Comment by luoxyhappy** [comment]
Thanks a lot
