### ISSUE TITLE
local_image_embedding

### ISSUE THREAD

**Issue by GloryyrolG** [antgroup/animate-x#8]
Hi @tanshuai0219 @Biao-Gong et. al.

thx for ur great work! may i ask for the reference in the main text of `local_image_embedding` cf. below? thx & rgds,

https://github.com/antgroup/animate-x/blob/fdc80909f911d8e487cb4e6847f2e4c6501b62af/animatex/model/unet_animate_x.py#L543

**Comment by tanshuai0219** [comment]
Hi, thanks for the interest in Animate-X.
`local_image_embedding` is not specified in the main text. But you can refer to `Unified noised input` in the paper "UniAnimate: Taming Unified Video Diffusion Models for Consistent Human Image Animation". Our implementation is based on [UniAnimate](https://github.com/ali-vilab/UniAnimate) .
